### ISSUE TITLE
phpmyadmin in merecat?

### ISSUE THREAD

**Issue by ricardoG08** [troglobit/merecat#18]
I open a new thread, phpmyadmin in mercat ?, not really, but if someone has been able to make "phpminiadmin" work in merecat I would appreciate it http://phpminiadmin.sourceforge.net/ , it's a simple script in php

**Comment by troglobit** [comment]
Not a PHP user myself.  But I did some work to get php-cgi to work earlier, just like other CGIs.  Dunno if you need env. variables or sth for phpminiadmin, but it's possible it works as is using the the latest GIT master.  Some info on PHP and CGI is in the man pages.

**Comment by troglobit** [comment]
Tested setting up Maria DB with phpMyAdmin today.  With the latest bug fixes I pushed today, it works ... :open_mouth: 

I used Debian 10, installed everything from scratch.  Used the default Apache first, just to bootstrap everything.  Then started Merecat on port 8080 instead of the default.   The only real adaptations I had to do, except for enabling PHP (with the correct CGI pattern), was to make sure to run merecat with sudo and set `username = www-data` in my merecat.conf ... otherwise the /var/lib/php/sessions cannot be read.
